// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Flight_Finder.Api.Models
{
    public partial class Bookings
    {
        public string BookingId { get; set; }
        public DateTime BookingDate { get; set; }
        public int NumberOfSeats { get; set; }
        public string FlightId { get; set; }
        public string UserId { get; set; }

        public virtual Itineraries Flight { get; set; }
        public virtual Users User { get; set; }
    }
}