// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Flight_Finder.Api.Models
{
    public partial class Booking
    {
        public string BookingId { get; set; }
        public DateTime BookingDate { get; set; }
        public string FlightId { get; set; }
        public string UserId { get; set; }
        public double Price { get; set; }
        public int Adults { get; set; }
        public int? Child { get; set; }

        public virtual Itinerary Flight { get; set; }
        public virtual User User { get; set; }
    }
}