// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Flight_Finder.Api.Models
{
    public partial class FlightRoute
    {
        public FlightRoute()
        {
            Itineraries = new HashSet<Itinerary>();
        }

        public string RouteId { get; set; }
        public string DepartureDestination { get; set; }
        public string ArrivalDestination { get; set; }

        public virtual ICollection<Itinerary> Itineraries { get; set; }
    }
}