// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Flight_Finder.Api.Models
{
    public partial class Itinerary
    {
        public Itinerary()
        {
            Bookings = new HashSet<Booking>();
        }

        public string FlightId { get; set; }
        public DateTime DepartureAt { get; set; }
        public DateTime ArrivalAt { get; set; }
        public int AvailableSeats { get; set; }
        public string RouteId { get; set; }
        public string Currency { get; set; }
        public double AdultPrice { get; set; }
        public double ChildPrice { get; set; }

        public virtual FlightRoute Route { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}