// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Populate_Data.Models
{
    public partial class FlightFinderDBContext : DbContext
    {
        public FlightFinderDBContext()
        {
        }

        public FlightFinderDBContext(DbContextOptions<FlightFinderDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FlightRoutes> FlightRoutes { get; set; }
        public virtual DbSet<Itinerary> Itinerary { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FlightRoutes>(entity =>
            {
                entity.HasKey(e => e.RouteId)
                    .HasName("PK__FlightRo__80979B4D9308333F");

                entity.Property(e => e.RouteId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.ArrivalDestination)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.DepartureDestination)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Itinerary>(entity =>
            {
                entity.HasKey(e => e.FlightId)
                    .HasName("PK__Itinerar__8A9E14EE7FE7B43F");

                entity.Property(e => e.FlightId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.ArrivalAt).HasColumnType("datetime");

                entity.Property(e => e.DepartureAt).HasColumnType("datetime");

                entity.Property(e => e.RouteId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.Route)
                    .WithMany(p => p.Itinerary)
                    .HasForeignKey(d => d.RouteId)
                    .HasConstraintName("FK__Itinerary__Route__398D8EEE");
            });

            modelBuilder.Entity<Prices>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Currency)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.FlightId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.Flight)
                    .WithMany()
                    .HasForeignKey(d => d.FlightId)
                    .HasConstraintName("FK__Prices__FlightId__3B75D760");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}