// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Populate_Data.Models
{
    public partial class FlightFinderDBContext : DbContext
    {
        public FlightFinderDBContext()
        {
        }

        public FlightFinderDBContext(DbContextOptions<FlightFinderDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FlightRoutes> FlightRoutes { get; set; }
        public virtual DbSet<Itineraries> Itineraries { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FlightRoutes>(entity =>
            {
                entity.HasKey(e => e.RouteId)
                    .HasName("PK__FlightRo__80979B4D9308333F");

                entity.Property(e => e.RouteId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.ArrivalDestination)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.DepartureDestination)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Itineraries>(entity =>
            {
                entity.HasKey(e => e.FlightId)
                    .HasName("PK__Itinerar__8A9E14EECCC0B374");

                entity.Property(e => e.FlightId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.ArrivalAt).HasColumnType("datetime");

                entity.Property(e => e.Currency)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.DepartureAt).HasColumnType("datetime");

                entity.Property(e => e.RouteId)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.Route)
                    .WithMany(p => p.Itineraries)
                    .HasForeignKey(d => d.RouteId)
                    .HasConstraintName("FK__Itinerari__Route__3E52440B");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}