// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Populate_Data.Models
{
    public partial class FlightRoutes
    {
        public FlightRoutes()
        {
            Itineraries = new HashSet<Itineraries>();
        }

        public string RouteId { get; set; }
        public string DepartureDestination { get; set; }
        public string ArrivalDestination { get; set; }

        public virtual ICollection<Itineraries> Itineraries { get; set; }
    }
}