// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Populate_Data.Models
{
    public partial class Prices
    {
        public string Currency { get; set; }
        public double Adult { get; set; }
        public double Child { get; set; }
        public string FlightId { get; set; }

        public virtual Itinerary Flight { get; set; }
    }
}